name: finsplore
description: Unified Finsplore Financial Management Platform
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  intl: ^0.20.2
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  easy_refresh: ^3.4.0
  json_annotation: ^4.9.0
  dio: ^5.4.3
  pretty_dio_logger: ^1.3.1 
  hive_ce: 2.10.1
  hive_ce_flutter: 2.2.0
  webview_flutter: ^4.10.0
  vector_math: ^2.1.4
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  jwt_decoder: ^2.0.1
  decimal: ^3.2.1
  animate_do: ^3.3.4
  flutter_animate: ^4.5.0
  glassmorphism: ^3.0.0
  shimmer: ^3.0.0
  lottie: ^3.1.2
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  golden_toolkit: ^0.15.0
  json_serializable: ^6.9.0
  build_runner: ^2.4.13
  hive_ce_generator: 1.8.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

  # Commented out until actual font files are available
  # fonts:
  # - family: ProximaNova
  #   fonts:
  #     - asset: assets/fonts/proximanova_regular.ttf
  #     - asset: assets/fonts/proximanova_bold.otf
  #       weight: 700

# Commented out until actual icon is available
# flutter_icons:
#   android: true
#   ios: true
#   image_path: "assets/icon/app_icon.png"
