// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:finsplore/local_storage/db_model/account_model.dart';
import 'package:finsplore/local_storage/db_model/asset_liability_model.dart';
import 'package:finsplore/local_storage/db_model/goal_model.dart';
import 'package:finsplore/local_storage/db_model/transaction_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AccountModelAdapter());
    registerAdapter(AssetLiabilityModelAdapter());
    registerAdapter(GoalModelAdapter());
    registerAdapter(TransactionModelAdapter());
  }
}
